name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/webapp:${{ github.run_number }}-${{ github.sha }}

    - name: push docker Image to registry 
      run: docker push lidorlg/webapp:${{ github.run_number }}-${{ github.sha }}
